POST http://localhost:3333/accounts
Content-Type: application/json

{
  "name": "Matheus Reinheimer",
  "email": "mreinheimer0@gmail.com",
  "password": "password123"
}

### @name authenticate

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "mreinheimer0@gmail.com",
  "password": "password123"
}