POST http://localhost:3333/accounts
Content-Type: application/json

{
  "name": "Raimer",
  "email": "raimer@example.com",
  "password": "password123"
}

### @name authenticate

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "raimer@example.com",
  "password": "password123"
}